export const OPENAPI_MCP_OPTIONS = Symbol('OPENAPI_MCP_OPTIONS');
export const OPENAPI_MCP_RUNTIME_OPTIONS = Symbol('OPENAPI_MCP_RUNTIME_OPTIONS');
export const OPENAPI_MCP_RUNTIME = Symbol('OPENAPI_MCP_RUNTIME');
export const OPENAPI_MCP_EXECUTOR = Symbol('OPENAPI_MCP_EXECUTOR');
